services:

  postgres:
    image: "postgres:13"
    restart: always
    volumes:
      - $HOME/MobSF/postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mobsf
    networks:
      - mobsf_network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mobsf
    networks:
      - mobsf_network

  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    restart: always
    volumes:
      - $HOME/MobSF/mobsf_data:/home/mobsf/.MobSF
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mobsf
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    healthcheck:
      test: curl -f http://localhost:8000/login/ || exit 1
    depends_on:
      - postgres
    networks:
      - mobsf_network

networks:
  mobsf_network:
    driver: bridge
