name: Socket Supply Chain Firewall
permissions:
  contents: read
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  socket-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: socketdev/action@v1
        with:
          mode: firewall
          firewall-version: latest

      - uses: actions/checkout@v5
      - uses: actions/setup-python@v3
      - name: Generate Requirements
        run: |
          python -m pip install poetry
          poetry self add poetry-plugin-export
          poetry export --without-hashes --format=requirements.txt > requirements.txt
          pip wheel --wheel-dir=yara-python-dex git+https://github.com/MobSF/yara-python-dex.git
      - name: Socket Firewall Scan
        run: |
          sfw pip install --no-index --find-links=yara-python-dex yara-python-dex
          sfw pip install -r requirements.txt
